#FAÇA UM PROGRAMA QUE LEIA UM NUMERO INTEIRO QUALQUER E MOSTRE NA TELA A SUA TABUADA.
n = int(input('Digite um numero: '))
#print('O numero digitado foi {}, sua tabuada é \n {} x {} = {} '.format(n, n, 1, n * 1 ))
print('-' * 10)
print('{} x {} = {} '.format(n, 1, n * 1))
print('{} x {} = {} '.format(n, 2, n * 2))
print('{} x {} = {} '.format(n, 3, n * 3))
print('{} x {} = {} '.format(n, 4, n * 4))
print('{} x {} = {} '.format(n, 5, n * 5))
print('{} x {} = {} '.format(n, 6, n * 6))
print('{} x {} = {} '.format(n, 7, n * 7))
print('{} x {} = {} '.format(n, 8, n * 8))
print('{} x {} = {} '.format(n, 9, n * 9))
print('{} x {} = {} '.format(n, 10, n * 10))
print('-' * 10)

