'''
DESAFIO
FAÇA UM PROGRAMA QUE LEIA UMA FRASE PELO TECLADO E MOSTRE:
-QUANTAS VEZES APARECE A LETRA A
-EM QUE POSICAO ELA APARECE A PRIMEIRA VEZ
-EM QUE POSICAO ELA APARECE A ULTIMA VEZ
'''
f = str(input('Digite sua frase: '))
print(f.count('a'))
print(f.find('a'))
