'''
CRIE UM PROGRAMA ONDE O USUARIO POSSA DIGITAR VARIOS VALORES NUMERICOS E CADASTRE-OS EM UMA LISTA.CASO O NUMERO
JÁ EXISTA LÁ DENTRO, ELE NAO SERA ADICIONADO.
NO FINAL,SERÃO EXIBIDOS TODOS OS VALORES UNICOS DIGITADOS, EM ORDEM CRESCENTE.
'''
