'''
FAÇA UM PROGRAMA QUE JOGUE PAR OU IMPAR COM O COMPUTADOR. O JOGO SÓ SERÁ INTERROMPIDO QUANDO O JOGADOR PERDER,
MOSTRANDO O TOTAL DE VITÓRIAS CONSECULTIVAS QUE ELE CONQUISTOU NO FINAL DO JOGO.
'''