'''
CRIE UM PROGRAMA QUE LEIA DOIS VALORES E MOSTRE UM MENU COMO AO LADO NA TELA:
SEU PROGRAMA DEVERÁ REALIZAR A OPERAÇ~~AO SOLICITADA EM CADA CASO.
[1] SOMAR
[2] MULTIPLICAR
[3] MAIOR
[4] NOVOS NUMEROS
[5] SAIR DO PROGRAMA
'''