'''
ESCREVA UM PROGRAMA QUE FAÇA O COMPUTADOR 'PENSAR' EM UM NUMERO INTEIRO ENTRE 0 E 5 E PEÇA PARA O USUARIO DESCOBRIR QUAL FOI O NUMERO
ESCOLHIDO PELO COMPUTADOR.
O PROGRAMA DEVERÁ ESCREVER NA TELA SE O USUARIO VENCEU OU PERDEU.
'''