'''
CRIE UM PROGRAMA QUE SIMULE O FUNCIONAMENTO DE UM CAIXA ELETRÔNICO.NO INICIO, PERGUNTE AO USUÁRIO QUAL SERÁ O
VALOR A SER SACADO( NUMERO INTEIRO) E O PROGRAMA VAI INFORMAR QUANTAS CÉDULAS DE CADA VALOR SERÃO ENTREGUES.
OBS:.CONSIDERE QUE O CAIXA POSSUI CÉDULAS DE $50,$20,$10,$1.
'''