'''
CRIE UM PROGRAMA ONDE O USUARIO POSSA DIGITAR CINCO VALORES NUMERICOS E CADASTRE-OS EM UMA LISTA,JA NA POSIÇAO
CORRETA DE INSERÇÃO (SEM USAR O SORT()).
NO FINAL, MOSTRE A LISTA ORDENADA NA TELA.
'''