'''
CRIE UM PROGRAMA QUE LEIA A IDADE E O SEXO DE VARIAS PESSOAS. A CADA PESSOA CADASTRADA , O PROGRAMA DEVERÁ
PERGUNTAR SE O USUÁRIO QUER OU NÃO CONTINUAR.NO FINAL,MOSTRE:
A- QUANTAS PESSOAS TEM MAIS DE 18 ANOS.
B- QUANTOS HOMENS FORAM CADASTRADOS.
C- QUANTAS MULHERES TEM MENOS DE 20 ANOS.
'''